<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Rememberly - RESTful Service</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
      <?php if (isset($name)) : ?>
          <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
          <?php endif; ?>
        <h1>Rememberly</h1>
        <div>A RESTful Service for Notes and Todolists</div>
            <p>Powered by <a href="http://www.slimframework.com">SlimFramework</a></p>

    </body>
</html>
